### PR TITLE
Convert hooks interpolation code to TypeScript

### PR DESCRIPTION
**Pull request by jacobrask**
The interpolation config might not be ideal for the public API yet, we might possibly want separate interfaces, but this is a start.

There are a couple of non-null assertions (`!`) in the `createInterpolation` function. I believe that if we handle those errors properly, several open issues might be solved. It's better if that's solved and reviewed separately though.

### CODE REVIEW

**Comment by drcmda** [comment]
This pull request **introduces 2 alerts** when merging 8e8bd64b8ba2adee63f4045fb17b9e3e50db1363 into ed87d4f85dec6e65dbdab3ffe86f08749ab2bb4e - [view on LGTM.com](https://lgtm.com/projects/g/react-spring/react-spring/rev/pr-5210297c26282fa4ae16ee176188dc02f71f0897)

**new alerts:**

* 2 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by drcmda** [comment]
@jacobrask wow, thanks so much, it looks really good! is this ready for merging?

**Comment by jacobrask** [comment]
I have some updates to the helper functions that I can add here as well, which will also fix the LGTM issues above

**Comment by jacobrask** [comment]
Should be good to merge now, I inspected the output bundles and differences are very minor

**Comment by drcmda** [comment]
@jacobrask i'm getting this error when trying to build

````
./src/targets/web/index.js → dist/web.js...
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
src/shared/helpers.ts (5:9)
3: export const is = {
4:   arr: Array.isArray,
5:   obj: (a: unknown): a is object =>
            ^
````

do you know what's the problem?

**Comment by drcmda** [comment]
nevermind, extensions was missing in the babel config, now compiles fine :)

**Pull request merged**
