### PR TITLE
Fix: HSL -> RGB Accuracy. 

### PR DESCRIPTION
**Pull request by ShanonJackson**
https://github.com/react-spring/react-spring/issues/938

### CODE REVIEW

**Comment by aleclarson** [comment]
Merged into #978

**Comment by aleclarson** [comment]
Now available in v9.0.0-rc.2 #985

**Comment by aleclarson** [comment]
This PR will be reverted in v9.0.0-rc.4 because it returns `rgb(255, 97, 97)` for `hsl(57, 100%, 69%)` when it should actually be `rgb(255, 247, 97)`. The previous implementation works as expected, at least in this case.

**Comment by ShanonJackson** [comment]
Might be worth just using the native DOM api to convert colors, it (should) always be right. However this wont work for SSR.
```
var div = document.createElement("div");
div.style.color = "hsl(57, 100%, 69%)"
console.log(div.style.color) // rgb(255, 247, 97);
```
where it always converts to RGB.

**Pull request closed without merging**
