### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by stephencorwin**
@drcmda @gsimone and I started a Discord server to help foster both internal + external communication. This adds an invite link banner to the readme to help spread the word about it.

Banner implementation from the official discord banner repo
https://github.com/dgibbs64/discord-banners

image

### CODE REVIEW

**Comment by aleclarson** [comment]
We recently switched from Spectrum to GitHub Discussions ([here](https://github.com/react-spring/react-spring/discussions)). Is there a reason you prefer Discord?

**Comment by stephencorwin** [comment]
Discord doesn't replace GitHub Discussions. Discord is for real-time communication whereas GitHub Discussions is better for async + search engine discovery.

Many tech communities have been leveraging Discord as a supplement to help grow community awareness.

You can see examples of other popular Discord servers here:
- [Reactiflux ](https://discord.gg/reactiflux)
  - 125,000 members and growing. Great resource for react help. [They started on Slack and moved to Discord back in 2015](https://reactjs.org/blog/2015/10/19/reactiflux-is-moving-to-discord.html). Article is a bit old, but the reason is still relevant.
- [Three.js](https://discord.com/invite/HF4UdyF)
  - This is actually run by [Mr. Doob](https://github.com/mrdoob). Probably a good one to join if you want to keep up-to-date with three.js happenings. Particularly relevant in the case of `react-three-fiber`.
- [TypeScript Community](https://discord.com/invite/typescript)
  - Fantastic resource for asking TS questions.

**Comment by stephencorwin** [comment]
Personally, I feel like it is easier to collaborate/strategize in real time. Async can be great too, but for quickly hashing something out, IRC text (or hopping into a voice channel) really speeds things up.

In addition, GH team discussion boards are very formal and "permanent". I think the design of that feature actually discourages communication within the team of maintainers. I'm definitely not trying to do away with Discussion boards, this merely supplements the community experience.

**Comment by drcmda** [comment]
i think github is fine for issues and long form trouble shooting. but i agree that something like discord could help us getting something like a community going. there's so much creative potential here and the people that use these projects are doing out of this world cool stuff with it, but there's no real feeling of a community still.

**Comment by drcmda** [comment]
@stephencorwin could you add it to the others as well?

**Pull request merged**
