### PR TITLE
Batch deletion of removed items

### PR DESCRIPTION
**Pull request by mart-jansink**
Batch the deletion of removed items after they transitioned out. See #461.

### CODE REVIEW

**Comment by drcmda** [comment]
could you checkout the hooks.8.x branch and see if this is still an issue? it's going to get all refactored soon and in the new branch it removes lazily by default already

**Comment by grrowl** [comment]
I'm still seeing this issue on `react-spring@8.0.8` using the `useTransition` hook. Would love to see this merged :)

**Comment by drcmda** [comment]
@grrowl could you make a minimal codesandbox to show the effect?

**Comment by grrowl** [comment]
Sure thing: this demo exhibits the behavior using hooks and the latest react-spring: https://codesandbox.io/s/my869ojmjj

**Comment by drcmda** [comment]
@grrowl could you give me a super quick rundown how you expect it to behave?

**Comment by grrowl** [comment]
Sorry, I didn't explain the problem exhibited by the demo.

When you click "Filter", we re-render with only the item "b". But notice, the item "b" moves into the space taken by "f", even though all the children are keyed and should maintain their position through transitions in and out. 

So, what we expect when changing the items array is rendering a list of (using punctuation to illustrate fading: 

* `[a] [b] [c] [d] [e] [f] [g]` => begin transition
* `.a. [b] .c. .d. .e. .f. .g.` => transition finishes
* `[b]`

The problem is the items are re-ordered when rendered through the "transition" phase as:

* `[a] [b] [c] [d] [e] [f] [g]` => begin transition
* `.a. .d. .e. .f. .g. [b] .c.` => transition finishes (`b` and `c` move to the end of the `transitions` array)
* `[b]`

In my example I included the `key` in item render since, especially when setting `unique: true`, elements' order should be maintained throughout renders.

**Comment by drcmda** [comment]
yeah, i think batch delete wouldn't have an effect on order, and it actually does batch delete now in some situations. if you want to look at it, that would be amazing as my time's limited right now. it's here somewhere: https://github.com/react-spring/react-spring/blob/master/src/useTransition.js#L250-L259

here's how i debug stuff: https://github.com/react-spring/react-spring-examples/blob/master/README.md

**Pull request closed without merging**
