### PR TITLE
adds a TypeError to help new users avoid mixing strings and numbers

### PR DESCRIPTION
**Pull request by capaj**
as suggested in #401

### CODE REVIEW

**Comment by drcmda** [comment]
Nice idea, how about using "invariant" like the original animated (https://github.com/animatedjs/animated/blob/master/src/Interpolation.js). I think invariant will only apply to dev env and get removed in production.

**Comment by capaj** [comment]
Will amend it

**Comment by drcmda** [comment]
Maybe even https://www.npmjs.com/package/tiny-invariant , that way we don't inline the sprintf logic that invariant has.

**Comment by capaj** [comment]
@drcmda I am not sure if the build itself doesn't need more tweaking-I just added the `babel-plugin-dev-expression` plugin to babelrc

**Comment by drcmda** [comment]
I'll keep this up for a little while longer, i am thinking - maybe it's a good idea to add more of these warning, especially for interpolation

**Comment by aleclarson** [comment]
Closing this since v9 now warns when an interpolation fails:
https://github.com/react-spring/react-spring/blob/512f1e849d6d94729f0fce929e531e1a3249a318/packages/core/src/Controller.ts#L590-L595

**Pull request closed without merging**
